# https://upptime.js.org/docs/configuration

owner: decompme
repo: upptime

user-agent: decompme

sites:
  - name: decomp.me
    url: https://decomp.me
    maxResponseTime: 000

status-website:
  cname: status.decomp.me
  logoUrl: https://raw.githubusercontent.com/decompme/decomp.me/main/frontend/public/purplefrog-512.png
  name: decomp.me status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/decompme/decomp.me
    - title: Discord
      href: https://discord.gg/sutqNShRRs
  theme: night
